# Generated by Django 5.1.5 on 2025-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.TextField(default="44600"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.TextField(default="Kathmandu"),
        ),
    ]
