# Generated by Django 5.1.5 on 2025-03-15 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_order_postal_code_order_shipping_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_city",
            new_name="city",
        ),
    ]
