# Generated by Django 5.1.5 on 2025-02-19 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinic_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dermatologist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('About', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dermatologist_images/')),
                ('Specialization', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=100)),
                ('total_experience', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatologists', to='clinic.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='BookingClinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.dermatologist')),
            ],
        ),
    ]
