# Generated by Django 5.1.5 on 2025-02-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_dermatologist_bookingclinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='Specialization',
        ),
    ]
