# Generated by Django 5.1.5 on 2025-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0005_alter_clinic_image_alter_dermatologist_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingclinic",
            name="hair_report_pdf",
            field=models.FileField(blank=True, null=True, upload_to="hair_reports/"),
        ),
    ]
