# Generated by Django 5.1.5 on 2025-02-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hairline_pattern', models.IntegerField()),
                ('hair_fall_rate', models.IntegerField()),
                ('nutrition', models.IntegerField()),
                ('chemical_product_usage', models.IntegerField()),
                ('genetics', models.IntegerField()),
                ('past_chronic_illness', models.IntegerField()),
                ('sleep_disturbance', models.IntegerField()),
                ('water_quality_issue', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('food_habit', models.IntegerField()),
                ('hormonal_changes', models.IntegerField()),
                ('hair_care_habits', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('label', models.IntegerField()),
            ],
            options={
                'db_table': 'hairfall_data',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback', models.TextField()),
                ('details', models.TextField()),
                ('image', models.ImageField(default='default_user.jpg', upload_to='product_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
