# Generated by Django 5.1.5 on 2025-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hairline_pattern', models.IntegerField()),
                ('hair_fall_rate', models.IntegerField()),
                ('nutrition', models.IntegerField()),
                ('chemical_product_usage', models.IntegerField()),
                ('genetics', models.IntegerField()),
                ('past_chronic_illness', models.IntegerField()),
                ('sleep_disturbance', models.IntegerField()),
                ('water_quality_issue', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('food_habit', models.IntegerField()),
                ('hormonal_changes', models.IntegerField()),
                ('hair_care_habits', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('label', models.IntegerField()),
            ],
            options={
                'db_table': 'hairfall_data',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
