# Generated by Django 5.1.5 on 2025-02-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairfallprediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
