# Generated by Django 5.1.5 on 2025-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairfallprediction', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_user.jpg', upload_to='product_images/'),
        ),
    ]
