# Generated by Django 5.1.5 on 2025-02-16 06:52

import django.db.models.deletion
import hairfallprediction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairfallprediction', '0004_auto_20250216_1230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=hairfallprediction.models.get_default_author, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
