# Generated by Django 5.1.5 on 2025-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairfallprediction', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
