# Generated by Django 5.1.5 on 2025-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairfallprediction', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images/'),
        ),
    ]
