# Generated by Django 5.1.5 on 2025-02-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='specialization',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='preferences',
            new_name='role',
        ),
    ]
